import type { AppState, LogEntry, Raid } from '../types';
import { fmtMoney, warChest } from './stats';

// must mirror sanitizeSlug in server/vault-api.mjs — folder names depend on it
export const slugify = (s: string): string =>
  s.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '') || 'raid';

const day = (iso: string) => iso.slice(0, 10);
const hm = (mins: number) => (mins >= 60 ? `${Math.floor(mins / 60)}h ${mins % 60 ? `${mins % 60}m` : ''}`.trim() : `${mins}m`);

// Full contribution record for one protocol — written to vault-data/raids/<slug>/dossier.md
// and fed to the AI in win mode to write eligibility/win content.
export function buildRaidDossier(raid: Raid, entries: LogEntry[], state: AppState): string {
  const ordered = [...entries].sort((a, b) => +new Date(a.date) - +new Date(b.date));
  const minutes = ordered.reduce((n, e) => n + e.minutes, 0);
  const idName = (id: string) => state.identities.find((i) => i.id === id)?.name ?? '?';
  const lines: string[] = [];

  lines.push(`# ${raid.name} — Contribution Dossier`);
  lines.push('');
  lines.push(`> ${raid.sub}`);
  lines.push('');
  lines.push(`- **Status:** ${raid.status.toUpperCase()}${raid.statusLabel ? ` (${raid.statusLabel})` : ''}`);
  lines.push(`- **Chain:** ${raid.chain} · **Narrative:** ${raid.narrative} · **Risk:** ${raid.risk.toUpperCase()}`);
  lines.push(`- **Funding:** ${raid.brief.funding} · **Investors:** ${raid.brief.investors} · **Phase:** ${raid.brief.phase}`);
  if (raid.deadline) lines.push(`- **Next deadline:** ${raid.deadlineLabel ?? 'DEADLINE'} at ${raid.deadline.slice(0, 16).replace('T', ' ')}`);
  for (const [k, v] of Object.entries(raid.customFields)) lines.push(`- **${k}:** ${v}`);
  if (raid.brief.why) {
    lines.push('');
    lines.push(`**Thesis:** ${raid.brief.why}`);
  }
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push(`| Spent | Fees | Staked | Loot | Time invested | Contributions |`);
  lines.push(`| --- | --- | --- | --- | --- | --- |`);
  lines.push(`| ${fmtMoney(-raid.money.spent)} | ${fmtMoney(-raid.money.fees)} | ${fmtMoney(raid.money.staked)} | ${raid.money.looted > 0 ? `${raid.money.lootLabel} (${fmtMoney(raid.money.looted)})` : raid.money.lootLabel} | ${hm(minutes)} | ${ordered.length} |`);
  if (ordered.length) {
    lines.push('');
    lines.push(`First move ${day(ordered[0].date)} · latest ${day(ordered[ordered.length - 1].date)}.`);
  }
  lines.push('');
  lines.push('## Contribution log');
  lines.push('');
  if (!ordered.length) lines.push('_Nothing logged yet._');
  for (const e of ordered) {
    lines.push(`### ${day(e.date)} — ${e.what}`);
    const meta: string[] = [];
    if (e.why) meta.push(`why: ${e.why}`);
    meta.push(`identity: ${idName(e.identityId)}`, `chain: ${e.chain}`, `cost: ${fmtMoney(-e.cost)}`, `time: ${hm(e.minutes)}`);
    if (e.repeat && e.repeat !== 'once') meta.push(`repeats: ${e.repeat}`);
    if (e.loot) meta.push(`**LOOT: ${e.loot.label} (${fmtMoney(e.loot.value)})**`);
    lines.push(`- ${meta.join(' · ')}`);
    if (e.proofs.length) lines.push(`- proofs: ${e.proofs.join(', ')}`);
    for (const m of e.media ?? []) lines.push(`- screenshot: [${m.name}](${m.url})`);
    lines.push('');
  }
  const recurring = state.todo.filter((t) => t.raidId === raid.id);
  if (recurring.length) {
    lines.push('## Recurring duties');
    lines.push('');
    for (const t of recurring) lines.push(`- ${t.text} — ${t.cadence}${t.lastDone ? ` (last done ${t.lastDone})` : ''}`);
    lines.push('');
  }
  if (raid.tasks.length) {
    lines.push('## Hero tasks');
    lines.push('');
    for (const t of raid.tasks) lines.push(`- [${t.done ? 'x' : ' '}] ${t.text}`);
    lines.push('');
  }
  if (raid.links.length) {
    lines.push('## Links');
    lines.push('');
    for (const l of raid.links) lines.push(`- ${l.label}${l.url ? `: ${l.url}` : ''}`);
    lines.push('');
  }
  lines.push(`---`);
  lines.push(`_Generated by Airdrop Vault on ${new Date().toISOString().slice(0, 16).replace('T', ' ')}._`);
  return lines.join('\n');
}

// Everything across all protocols — written to vault-data/MASTER-DOSSIER.md
export function buildMasterDossier(state: AppState): string {
  const wc = warChest(state);
  const head = [
    `# Airdrop Vault — Master Dossier`,
    '',
    `All contributions across ${state.raids.length} raids · ${state.entries.length} logged moves.`,
    '',
    `**War chest:** spent ${fmtMoney(-wc.spent)} · looted ${fmtMoney(wc.looted)} · staked ${fmtMoney(wc.staked)} · net ${fmtMoney(wc.net)}`,
    '',
  ].join('\n');
  const sections = state.raids.map((r) =>
    buildRaidDossier(r, state.entries.filter((e) => e.raidId === r.id), state),
  );
  return [head, ...sections].join('\n\n---\n\n');
}

export interface DossierBundle {
  master: string;
  raids: { slug: string; name: string; md: string }[];
}

export function buildAllDossiers(state: AppState): DossierBundle {
  return {
    master: buildMasterDossier(state),
    raids: state.raids.map((r) => ({
      slug: slugify(r.name),
      name: r.name,
      md: buildRaidDossier(r, state.entries.filter((e) => e.raidId === r.id), state),
    })),
  };
}

export function downloadText(filename: string, text: string, mime = 'text/markdown'): void {
  const blob = new Blob([text], { type: mime });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}
